name: sinna
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  avatar_glow: ^2.0.2
  cloud_firestore: ^6.0.0
  cloud_functions: ^6.0.0
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.4.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  flutter_vector_icons: ^2.0.0
  go_router: ^16.0.0
  intl_phone_field: ^3.2.0
  lottie: ^3.3.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  screen_protector: ^1.4.2+1
  syncfusion_flutter_pdfviewer: ^31.1.18
  timelines_plus: ^1.0.7
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  webview_flutter: ^4.13.0
  youtube_player_flutter: ^9.1.2
  youtube_player_iframe: ^5.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
