// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh2q9v64kHpv0M1PgyEbGSKv13xaFSQF8',
    appId: '1:794122729438:web:32a4191de90be4acc00f4f',
    messagingSenderId: '794122729438',
    projectId: 'class-one-9958e',
    authDomain: 'class-one-9958e.firebaseapp.com',
    storageBucket: 'class-one-9958e.firebasestorage.app',
    measurementId: 'G-H524LG5M59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgEmaTSCdML9Q92JupyxcylC-bladI1P8',
    appId: '1:794122729438:android:e196933dee38ea5cc00f4f',
    messagingSenderId: '794122729438',
    projectId: 'class-one-9958e',
    storageBucket: 'class-one-9958e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNTFayy7yxbPJvWA4mxpWUV2FuuBvcbLU',
    appId: '1:794122729438:ios:368dd5d1f050488fc00f4f',
    messagingSenderId: '794122729438',
    projectId: 'class-one-9958e',
    storageBucket: 'class-one-9958e.firebasestorage.app',
    iosBundleId: 'com.example.sinna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNTFayy7yxbPJvWA4mxpWUV2FuuBvcbLU',
    appId: '1:794122729438:ios:368dd5d1f050488fc00f4f',
    messagingSenderId: '794122729438',
    projectId: 'class-one-9958e',
    storageBucket: 'class-one-9958e.firebasestorage.app',
    iosBundleId: 'com.example.sinna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh2q9v64kHpv0M1PgyEbGSKv13xaFSQF8',
    appId: '1:794122729438:web:676b62f7f015721fc00f4f',
    messagingSenderId: '794122729438',
    projectId: 'class-one-9958e',
    authDomain: 'class-one-9958e.firebaseapp.com',
    storageBucket: 'class-one-9958e.firebasestorage.app',
    measurementId: 'G-2MG78LZ5WB',
  );
}
